name: Create ADR

on:
  workflow_dispatch:
    inputs:
      adr-name:
        description: "Name of the new ADR"
        required: true
        type: string
      supersedes:
        description: "Number of the superseding ADR (leave empty if none)"
        required: false
        type: string
        default: ""

jobs:
  create-adr:
    name: Create new Architecture Decision Record
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v3.2.0
        with:
          token: ${{ secrets.ADMIN_REPO_TOKEN }}
      
      - name: Download and install helper
        run: |
          cd "$RUNNER_TEMP"
          wget -O helper.zip "https://github.com/npryce/adr-tools/archive/refs/tags/3.0.0.zip"
          unzip helper.zip
          echo "$(pwd)/adr-tools-3.0.0/src/" >> $GITHUB_PATH

      - name: Add new ADR
        env:
          ADR_NAME: "${{ inputs.adr-name }}"
          SUPERSEDING_ADR: "${{ inputs.supersedes }}"
        run: |
          echo "ADR name: ${ADR_NAME}"
          echo "Superseding ADR: ${SUPERSEDING_ADR}"
          if [ -n "$SUPERSEDING_ADR" ]; then
            echo "Add new ADR with superseding"
            adr new -s "$SUPERSEDING_ADR" "$ADR_NAME"
          else
            echo "Add new ADR without superseding"
            adr new "$ADR_NAME"
          fi
      
      - name: Commit changes
        env:
          ADR_NAME: "${{ inputs.adr-name }}"
        run: |
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "feat(adr): Add ADR '${ADR_NAME}'"
          git push
